import { Metadata } from "next";

import WildBody from "@/ui/wild_kingdom/body/WildBody";


export const metadata: Metadata = {
  title: 'The Wild Kingdom',
  description: 'Generated by create next app',
}

const Pets = () => {


    return (
        <>
            <WildBody />
        </>
    )
}
export default Pets;
