import { Metadata } from "next"


export const metadata: Metadata = {
  title: 'Awesome Woods',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div>
      AWESOME WOODS!
    </div>
  )
}
export default page
