import { Metadata } from "next"

import AwesomeBody from "@/ui/awesome_woods/AwesomeBody";


export const metadata: Metadata = {
  title: 'Awesome Woods',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <>
      <AwesomeBody/>
    </>
  )
};
export default page;
